name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

    
permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
   
    environment: Dev

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.URL }}
        app-id: ${{ secrets.CLIENTID }}
        client-secret: ${{ secrets.SECRET }}
        tenant-id: ${{ secrets.TENANTID }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.URL }}
        app-id: ${{ secrets.CLIENTID }}
        client-secret: ${{ secrets.SECRET }}
        tenant-id: ${{ secrets.TENANTID }}
        solution-name: ALMDemo
        solution-output-file: out/exported/ALMDemo.zip

    - name: export-solution action Managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.URL }}
        app-id: ${{ secrets.CLIENTID }}
        client-secret: ${{ secrets.SECRET }}
        tenant-id: ${{ secrets.TENANTID }}
        solution-name: ALMDemo
        managed: true
        solution-output-file: out/exported/ALMDemo_managed.zip
        

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ALMDemo.zip
        solution-folder: out/solutions/ALMDemo
        solution-type: Both
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMDemo
        solution-target-folder: solutions/ALMDemo
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
  






  
  

        


